#!/usr/bin/env bash
#
# Create a Git tag
#
# Example:
#   ./git-create-tag -v 1.2.3

set -e

while getopts ":v:" opt; do
  case $opt in
    v)
      version=$OPTARG
      ;;
  esac
done

[[ -z ${version} ]] && echo "missing version" && exit 1

echo "creating git tag: ${version}"

git --git-dir=${CI_WORKDIR}/.git tag -a ${version} -m "${version}" 
git --git-dir=${CI_WORKDIR}/.git push origin ${version}
